# Generated by Django 4.2.30 on 2026-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='import_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='track',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
