# Generated by Django 4.2.30 on 2026-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_import_source_track_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file_low',
            field=models.FileField(blank=True, null=True, upload_to='audio/low/'),
        ),
    ]
