from django.urls import path
from rest_framework.routers import DefaultRouter

from apps.channels.api.views import (
    ChannelAuditExportView,
    ChannelAuditLogView,
    ChannelChatPinView,
    ChannelChatView,
    ChannelCloseView,
    ChannelControlView,
    ChannelInviteRotateView,
    ChannelInviteView,
    ChannelJoinFromLinkView,
    ChannelJoinRequestApproveView,
    ChannelJoinRequestListView,
    ChannelJoinRequestRejectView,
    ChannelJoinView,
    ChannelLeaveView,
    ChannelMemberManageView,
    ChannelMembersView,
    ChannelNotificationPreferenceView,
    ChannelPartyRecapView,
    ChannelPlaybackHistoryView,
    ChannelPlayPlaylistView,
    ChannelPlayTrackView,
    ChannelPlaylistSuggestionView,
    ChannelPublicLinkRotateView,
    ChannelQueueItemManageView,
    ChannelQueueJumpView,
    ChannelQueueUpvoteView,
    ChannelQueueView,
    ChannelReopenView,
    ChannelSettingsView,
    ChannelSimilarTracksView,
    ChannelShufflePlayView,
    ChannelStateView,
    ChannelTrackReactionView,
    ChannelViewSet,
)
from apps.channels.api.room_tools import ChannelQueueImportShareView, ChannelSessionExportPlaylistView

router = DefaultRouter()
router.register("channels", ChannelViewSet, basename="channel")

urlpatterns = [
    path("channels/<int:channel_id>/state", ChannelStateView.as_view()),
    path("channels/<int:channel_id>/control", ChannelControlView.as_view()),
    path("channels/join-from-link", ChannelJoinFromLinkView.as_view()),
    path("channels/<int:channel_id>/join-requests", ChannelJoinRequestListView.as_view()),
    path("channels/<int:channel_id>/join-requests/<int:request_id>/approve", ChannelJoinRequestApproveView.as_view()),
    path("channels/<int:channel_id>/join-requests/<int:request_id>/reject", ChannelJoinRequestRejectView.as_view()),
    path("channels/<int:channel_id>/join", ChannelJoinView.as_view()),
    path("channels/<int:channel_id>/leave", ChannelLeaveView.as_view()),
    path("channels/<int:channel_id>/close", ChannelCloseView.as_view()),
    path("channels/<int:channel_id>/reopen", ChannelReopenView.as_view()),
    path("channels/<int:channel_id>/invite", ChannelInviteView.as_view()),
    path("channels/<int:channel_id>/invite/rotate", ChannelInviteRotateView.as_view()),
    path("channels/<int:channel_id>/public-link/rotate", ChannelPublicLinkRotateView.as_view()),
    path("channels/<int:channel_id>/tracks/similar", ChannelSimilarTracksView.as_view()),
    path("channels/<int:channel_id>/chat", ChannelChatView.as_view()),
    path("channels/<int:channel_id>/chat/pin", ChannelChatPinView.as_view()),
    path("channels/<int:channel_id>/track-reactions", ChannelTrackReactionView.as_view()),
    path("channels/<int:channel_id>/party-recap", ChannelPartyRecapView.as_view()),
    path("channels/<int:channel_id>/history", ChannelPlaybackHistoryView.as_view()),
    path("channels/<int:channel_id>/audit-log", ChannelAuditLogView.as_view()),
    path("channels/<int:channel_id>/audit-log/export", ChannelAuditExportView.as_view()),
    path("channels/<int:channel_id>/suggestions", ChannelPlaylistSuggestionView.as_view()),
    path("channels/<int:channel_id>/notification-settings", ChannelNotificationPreferenceView.as_view()),
    path("channels/<int:channel_id>/settings", ChannelSettingsView.as_view()),
    path("channels/<int:channel_id>/members", ChannelMembersView.as_view()),
    path("channels/<int:channel_id>/members/<int:member_id>", ChannelMemberManageView.as_view()),
    path("channels/<int:channel_id>/playlists/shuffle", ChannelShufflePlayView.as_view()),
    path("channels/<int:channel_id>/playlists/<int:playlist_id>/play", ChannelPlayPlaylistView.as_view()),
    path("channels/<int:channel_id>/tracks/<int:track_id>/play", ChannelPlayTrackView.as_view()),
    path("channels/<int:channel_id>/queue", ChannelQueueView.as_view()),
    path("channels/<int:channel_id>/queue/<int:item_id>", ChannelQueueItemManageView.as_view()),
    path("channels/<int:channel_id>/queue/<int:item_id>/jump", ChannelQueueJumpView.as_view()),
    path("channels/<int:channel_id>/queue/<int:item_id>/upvote", ChannelQueueUpvoteView.as_view()),
    path("channels/<int:channel_id>/queue/import-share", ChannelQueueImportShareView.as_view()),
    path("channels/<int:channel_id>/session/export-playlist", ChannelSessionExportPlaylistView.as_view()),
    *router.urls,
]
