# Generated by Django 4.2.30 on 2026-05-30 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stream_channels', '0014_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0003_track_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('lifetime_listen_seconds', models.PositiveBigIntegerField(default=0)),
                ('streak_days', models.PositiveSmallIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_listen_seconds', models.PositiveBigIntegerField(default=0)),
                ('total_play_events', models.PositiveIntegerField(default=0)),
                ('unique_listener_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='stream_channels.channel')),
            ],
            options={
                'verbose_name_plural': 'Channel analytics',
            },
        ),
        migrations.CreateModel(
            name='UserChannelListenStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_seconds', models.PositiveBigIntegerField(default=0)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('last_listen_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_listen_stats', to='stream_channels.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listen_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['channel', '-listen_seconds'], name='analytics_u_channel_13bfc1_idx')],
                'unique_together': {('channel', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GamificationPointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('listen', 'Listen'), ('chat', 'Chat'), ('suggestion', 'Suggestion'), ('reaction', 'Reaction'), ('blind_guess', 'Blind guess'), ('referral', 'Referral'), ('daily', 'Daily bonus')], max_length=32)),
                ('points', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream_channels.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_g_user_id_140417_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelTrackListenStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_seconds', models.PositiveBigIntegerField(default=0)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_listen_stats', to='stream_channels.channel')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listen_stats', to='tracks.track')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', '-listen_seconds'], name='analytics_c_channel_b18e5d_idx')],
                'unique_together': {('channel', 'track')},
            },
        ),
    ]
