# Generated by Django 4.2.16 on 2026-05-15 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracks", "0002_track_genre_track_tags"),
        ("stream_channels", "0008_channelchatmessage_edit_delete_reaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(blank=True, default="", max_length=64)),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChannelNotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("muted", models.BooleanField(default=False)),
                ("notify_room_started", models.BooleanField(default=True)),
                ("notify_queue_turn", models.BooleanField(default=True)),
                ("notify_skip_threshold", models.BooleanField(default=True)),
                ("notify_moderation", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChannelPlaylistSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChannelTrackReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emoji", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="channelchatmessage",
            new_name="stream_chan_channel_a7ab52_idx",
            old_name="stream_chan_chat_ch_id",
        ),
        migrations.RenameIndex(
            model_name="channelchatmessagereaction",
            new_name="stream_chan_message_e2c60b_idx",
            old_name="stream_chan_chat_rx_msg_id",
        ),
        migrations.RenameIndex(
            model_name="webpushsubscription",
            new_name="stream_chan_user_id_f79fd6_idx",
            old_name="stream_chan_push_user_id",
        ),
        migrations.AddField(
            model_name="channelchatmessage",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="channelchatmessage",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="channelchatmessage",
            name="pinned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_channel_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="channelchatmessage",
            index=models.Index(fields=["channel", "is_pinned"], name="stream_chan_channel_369fc1_idx"),
        ),
        migrations.AddField(
            model_name="channeltrackreaction",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_reactions",
                to="stream_channels.channel",
            ),
        ),
        migrations.AddField(
            model_name="channeltrackreaction",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="channel_reactions", to="tracks.track"
            ),
        ),
        migrations.AddField(
            model_name="channeltrackreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_track_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channelplaylistsuggestion",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_suggestions",
                to="stream_channels.channel",
            ),
        ),
        migrations.AddField(
            model_name="channelplaylistsuggestion",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_playlist_suggestions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channelplaylistsuggestion",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_playlist_suggestions",
                to="tracks.track",
            ),
        ),
        migrations.AddField(
            model_name="channelplaylistsuggestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_suggestions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channelnotificationpreference",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to="stream_channels.channel",
            ),
        ),
        migrations.AddField(
            model_name="channelnotificationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channelauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channelauditlog",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="stream_channels.channel"
            ),
        ),
        migrations.AddIndex(
            model_name="channeltrackreaction",
            index=models.Index(fields=["channel", "track", "created_at"], name="stream_chan_channel_dc42fe_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="channeltrackreaction",
            unique_together={("channel", "track", "user", "emoji")},
        ),
        migrations.AddIndex(
            model_name="channelplaylistsuggestion",
            index=models.Index(fields=["channel", "status", "-created_at"], name="stream_chan_channel_a8233c_idx"),
        ),
        migrations.AddIndex(
            model_name="channelnotificationpreference",
            index=models.Index(fields=["channel", "user"], name="stream_chan_channel_81c727_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="channelnotificationpreference",
            unique_together={("user", "channel")},
        ),
        migrations.AddIndex(
            model_name="channelauditlog",
            index=models.Index(fields=["channel", "-created_at"], name="stream_chan_channel_1ec338_idx"),
        ),
    ]
