# Generated by Django 4.2.30 on 2026-05-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_channels', '0013_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channelchatban',
            new_name='stream_chan_channel_be5aa7_idx',
            old_name='stream_chan_channel_ban_idx',
        ),
        migrations.RenameIndex(
            model_name='channelchatreport',
            new_name='stream_chan_channel_49c14a_idx',
            old_name='stream_chan_channel_8a1f2d_idx',
        ),
    ]
