# Generated by Django 4.2.30 on 2026-05-30 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_import_source_track_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream_channels', '0014_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelBlindGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_text', models.CharField(max_length=255)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_guesses', to='stream_channels.channel')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_guesses', to='tracks.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blind_guesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['channel', '-created_at'], name='stream_chan_channel_053424_idx')],
                'unique_together': {('channel', 'user', 'track')},
            },
        ),
    ]
