# Generated by Django 4.2.30 on 2026-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_channels', '0015_channelblindguess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('moderator', 'Moderator'), ('dj', 'DJ'), ('member', 'Member')], default='member', max_length=16),
        ),
    ]
