from django.urls import include, path
from rest_framework.routers import DefaultRouter

from apps.tracks.upload_views import TrackUploadChunkView, TrackUploadFinalizeView, TrackUploadInitView

from apps.common.views import (
    LoginView,
    LogoutView,
    MeView,
    UserNotificationSettingsView,
    WebPushSubscriptionView,
    UsersListView,
    RegisterView,
    ChannelControlView,
    ChannelInviteView,
    ChannelInviteRotateView,
    ChannelJoinFromLinkView,
    ChannelJoinRequestApproveView,
    ChannelJoinRequestListView,
    ChannelJoinRequestRejectView,
    ChannelJoinView,
    ChannelNotificationPreferenceView,
    ChannelPlaybackHistoryView,
    ChannelAuditLogView,
    ChannelPlaylistSuggestionView,
    ChannelChatPinView,
    ChannelTrackReactionView,
    ChannelCloseView,
    ChannelLeaveView,
    ChannelReopenView,
    ChannelMemberManageView,
    ChannelMembersView,
    ChannelPlayPlaylistView,
    ChannelPlayTrackView,
    ChannelShufflePlayView,
    ChannelQueueItemManageView,
    ChannelQueueJumpView,
    ChannelQueueView,
    ChannelPublicLinkRotateView,
    ChannelSettingsView,
    ChannelSimilarTracksView,
    ChannelChatView,
    ChannelStateView,
    ChannelViewSet,
    PlaylistItemViewSet,
    PlaylistViewSet,
    TrackViewSet,
    TrackSharePermissionsView,
    api_time,
    auth_csrf,
)

router = DefaultRouter()
router.register("channels", ChannelViewSet, basename="channel")
router.register("tracks", TrackViewSet, basename="track")
router.register("playlists", PlaylistViewSet, basename="playlist")
router.register("playlist-items", PlaylistItemViewSet, basename="playlist-item")

urlpatterns = [
    path("time", api_time),
    path("auth/csrf", auth_csrf),
    path("auth/register", RegisterView.as_view()),
    path("auth/login", LoginView.as_view()),
    path("auth/logout", LogoutView.as_view()),
    path("auth/me", MeView.as_view()),
    path("auth/me/notification-settings", UserNotificationSettingsView.as_view()),
    path("auth/me/push-subscription", WebPushSubscriptionView.as_view()),
    path("auth/users", UsersListView.as_view()),
    path("channels/<int:channel_id>/state", ChannelStateView.as_view()),
    path("channels/<int:channel_id>/control", ChannelControlView.as_view()),
    path("channels/join-from-link", ChannelJoinFromLinkView.as_view()),
    path("channels/<int:channel_id>/join-requests", ChannelJoinRequestListView.as_view()),
    path("channels/<int:channel_id>/join-requests/<int:request_id>/approve", ChannelJoinRequestApproveView.as_view()),
    path("channels/<int:channel_id>/join-requests/<int:request_id>/reject", ChannelJoinRequestRejectView.as_view()),
    path("channels/<int:channel_id>/join", ChannelJoinView.as_view()),
    path("channels/<int:channel_id>/leave", ChannelLeaveView.as_view()),
    path("channels/<int:channel_id>/close", ChannelCloseView.as_view()),
    path("channels/<int:channel_id>/reopen", ChannelReopenView.as_view()),
    path("channels/<int:channel_id>/invite", ChannelInviteView.as_view()),
    path("channels/<int:channel_id>/invite/rotate", ChannelInviteRotateView.as_view()),
    path("channels/<int:channel_id>/public-link/rotate", ChannelPublicLinkRotateView.as_view()),
    path("channels/<int:channel_id>/tracks/similar", ChannelSimilarTracksView.as_view()),
    path("channels/<int:channel_id>/chat", ChannelChatView.as_view()),
    path("channels/<int:channel_id>/chat/pin", ChannelChatPinView.as_view()),
    path("channels/<int:channel_id>/track-reactions", ChannelTrackReactionView.as_view()),
    path("channels/<int:channel_id>/history", ChannelPlaybackHistoryView.as_view()),
    path("channels/<int:channel_id>/audit-log", ChannelAuditLogView.as_view()),
    path("channels/<int:channel_id>/suggestions", ChannelPlaylistSuggestionView.as_view()),
    path("channels/<int:channel_id>/notification-settings", ChannelNotificationPreferenceView.as_view()),
    path("channels/<int:channel_id>/settings", ChannelSettingsView.as_view()),
    path("channels/<int:channel_id>/members", ChannelMembersView.as_view()),
    path("channels/<int:channel_id>/members/<int:member_id>", ChannelMemberManageView.as_view()),
    path("channels/<int:channel_id>/playlists/shuffle", ChannelShufflePlayView.as_view()),
    path("channels/<int:channel_id>/playlists/<int:playlist_id>/play", ChannelPlayPlaylistView.as_view()),
    path("channels/<int:channel_id>/tracks/<int:track_id>/play", ChannelPlayTrackView.as_view()),
    path("channels/<int:channel_id>/queue", ChannelQueueView.as_view()),
    path("channels/<int:channel_id>/queue/<int:item_id>", ChannelQueueItemManageView.as_view()),
    path("channels/<int:channel_id>/queue/<int:item_id>/jump", ChannelQueueJumpView.as_view()),
    path("tracks/upload/init", TrackUploadInitView.as_view()),
    path("tracks/upload/<uuid:upload_id>/chunk", TrackUploadChunkView.as_view()),
    path("tracks/upload/<uuid:upload_id>/finalize", TrackUploadFinalizeView.as_view()),
    path("tracks/<int:track_id>/share-permissions", TrackSharePermissionsView.as_view()),
    path("", include(router.urls)),
]
