from django.urls import include, path
from rest_framework.routers import DefaultRouter

from apps.tracks.upload_views import (
    TrackUploadChunkView,
    TrackUploadFinalizeView,
    TrackUploadInitView,
    TrackUploadStatusView,
)

from apps.common.admin_views import (
    AdminBadgeDetailView,
    AdminBadgesView,
    AdminChannelsView,
    AdminHealthView,
    AdminOverviewView,
    AdminUserDetailView,
    AdminUsersView,
)
from apps.common.support_views import (
    SupportCategoriesView,
    SupportStaffUsersView,
    SupportTicketDetailView,
    SupportTicketMessagesView,
    SupportTicketsView,
)
from apps.common.health import HealthView
from apps.common.metrics import MetricsView
from apps.common.openapi_schema import OpenApiSchemaView
from apps.common.dashboard_views import MeChannelsOnlineView, MeChannelsPendingSuggestionsView
from apps.common.discovery_views import (
    ChannelFollowView,
    GlobalSearchView,
    MePublicProfileView,
    PlaylistShareImportView,
    PlaylistShareLinkView,
    PlaylistSharePreviewView,
    PremiumLimitsView,
    PublicUserProfileView,
    TrackFacetsView,
)
from apps.common.moderation_views import (
    ChannelChatBanStatusView,
    ChannelChatBanView,
    ChannelChatReportView,
    ChannelModerationReportsView,
)
from apps.common.social_expansion_views import (
    ChannelQueueImportShareView,
    ChannelSessionExportPlaylistView,
    ExploreFeedView,
    FollowingChannelsFeedView,
    UserFollowView,
)
from apps.common.views import (
    LoginView,
    LogoutView,
    MeView,
    UserPasswordChangeView,
    UserNotificationSettingsView,
    WebPushSubscriptionView,
    WebPushTestView,
    UsersListView,
    RegisterView,
    ChannelControlView,
    ChannelInviteView,
    ChannelInviteRotateView,
    ChannelJoinFromLinkView,
    ChannelJoinRequestApproveView,
    ChannelJoinRequestListView,
    ChannelJoinRequestRejectView,
    ChannelJoinView,
    ChannelNotificationPreferenceView,
    ChannelPartyRecapView,
    ChannelPlaybackHistoryView,
    ChannelAuditExportView,
    ChannelAuditLogView,
    ChannelPlaylistSuggestionView,
    ChannelChatPinView,
    ChannelTrackReactionView,
    ChannelCloseView,
    ChannelLeaveView,
    ChannelReopenView,
    ChannelMemberManageView,
    ChannelMembersView,
    ChannelPlayPlaylistView,
    ChannelPlayTrackView,
    ChannelShufflePlayView,
    ChannelQueueItemManageView,
    ChannelQueueJumpView,
    ChannelQueueUpvoteView,
    ChannelQueueView,
    ChannelPublicLinkRotateView,
    ChannelSettingsView,
    ChannelSimilarTracksView,
    ChannelChatView,
    ChannelStateView,
    ChannelViewSet,
    PlaylistItemViewSet,
    PlaylistViewSet,
    TrackViewSet,
    TrackSharePermissionsView,
    api_time,
    auth_csrf,
)

router = DefaultRouter()
router.register("channels", ChannelViewSet, basename="channel")
router.register("tracks", TrackViewSet, basename="track")
router.register("playlists", PlaylistViewSet, basename="playlist")
router.register("playlist-items", PlaylistItemViewSet, basename="playlist-item")

urlpatterns = [
    path("health", HealthView.as_view()),
    path("metrics", MetricsView.as_view()),
    path("schema", OpenApiSchemaView.as_view()),
    path("time", api_time),
    path("auth/csrf", auth_csrf),
    path("auth/register", RegisterView.as_view()),
    path("auth/login", LoginView.as_view()),
    path("auth/logout", LogoutView.as_view()),
    path("auth/me", MeView.as_view()),
    path("auth/me/public-profile", MePublicProfileView.as_view()),
    path("auth/me/premium-limits", PremiumLimitsView.as_view()),
    path("search/global", GlobalSearchView.as_view()),
    path("tracks/facets", TrackFacetsView.as_view()),
    path("users/<str:username>/profile", PublicUserProfileView.as_view()),
    path("playlists/<int:playlist_id>/share", PlaylistShareLinkView.as_view()),
    path("playlists/share/<uuid:token>", PlaylistSharePreviewView.as_view()),
    path("channels/<int:channel_id>/playlists/import-share", PlaylistShareImportView.as_view()),
    path("channels/<int:channel_id>/follow", ChannelFollowView.as_view()),
    path("me/following-channels", FollowingChannelsFeedView.as_view()),
    path("me/channels-online", MeChannelsOnlineView.as_view()),
    path("me/channels-pending-suggestions", MeChannelsPendingSuggestionsView.as_view()),
    path("explore", ExploreFeedView.as_view()),
    path("users/<str:username>/follow", UserFollowView.as_view()),
    path("channels/<int:channel_id>/queue/import-share", ChannelQueueImportShareView.as_view()),
    path("channels/<int:channel_id>/session/export-playlist", ChannelSessionExportPlaylistView.as_view()),
    path("auth/me/password", UserPasswordChangeView.as_view()),
    path("auth/me/notification-settings", UserNotificationSettingsView.as_view()),
    path("auth/me/push-subscription", WebPushSubscriptionView.as_view()),
    path("auth/me/push-test", WebPushTestView.as_view()),
    path("auth/users", UsersListView.as_view()),
    path("admin/overview", AdminOverviewView.as_view()),
    path("admin/users", AdminUsersView.as_view()),
    path("admin/users/<int:user_id>", AdminUserDetailView.as_view()),
    path("admin/badges", AdminBadgesView.as_view()),
    path("admin/badges/<int:badge_id>", AdminBadgeDetailView.as_view()),
    path("admin/channels", AdminChannelsView.as_view()),
    path("admin/health", AdminHealthView.as_view()),
    path("support/categories", SupportCategoriesView.as_view()),
    path("support/tickets", SupportTicketsView.as_view()),
    path("support/tickets/<int:ticket_id>", SupportTicketDetailView.as_view()),
    path("support/tickets/<int:ticket_id>/messages", SupportTicketMessagesView.as_view()),
    path("support/staff-users", SupportStaffUsersView.as_view()),
    path("channels/<int:channel_id>/state", ChannelStateView.as_view()),
    path("channels/<int:channel_id>/control", ChannelControlView.as_view()),
    path("channels/join-from-link", ChannelJoinFromLinkView.as_view()),
    path("channels/<int:channel_id>/join-requests", ChannelJoinRequestListView.as_view()),
    path("channels/<int:channel_id>/join-requests/<int:request_id>/approve", ChannelJoinRequestApproveView.as_view()),
    path("channels/<int:channel_id>/join-requests/<int:request_id>/reject", ChannelJoinRequestRejectView.as_view()),
    path("channels/<int:channel_id>/join", ChannelJoinView.as_view()),
    path("channels/<int:channel_id>/leave", ChannelLeaveView.as_view()),
    path("channels/<int:channel_id>/close", ChannelCloseView.as_view()),
    path("channels/<int:channel_id>/reopen", ChannelReopenView.as_view()),
    path("channels/<int:channel_id>/invite", ChannelInviteView.as_view()),
    path("channels/<int:channel_id>/invite/rotate", ChannelInviteRotateView.as_view()),
    path("channels/<int:channel_id>/public-link/rotate", ChannelPublicLinkRotateView.as_view()),
    path("channels/<int:channel_id>/tracks/similar", ChannelSimilarTracksView.as_view()),
    path("channels/<int:channel_id>/chat", ChannelChatView.as_view()),
    path("channels/<int:channel_id>/chat/report", ChannelChatReportView.as_view()),
    path("channels/<int:channel_id>/chat/pin", ChannelChatPinView.as_view()),
    path("channels/<int:channel_id>/moderation/reports", ChannelModerationReportsView.as_view()),
    path("channels/<int:channel_id>/moderation/bans", ChannelChatBanStatusView.as_view()),
    path("channels/<int:channel_id>/moderation/bans/<int:user_id>", ChannelChatBanView.as_view()),
    path("channels/<int:channel_id>/track-reactions", ChannelTrackReactionView.as_view()),
    path("channels/<int:channel_id>/party-recap", ChannelPartyRecapView.as_view()),
    path("channels/<int:channel_id>/history", ChannelPlaybackHistoryView.as_view()),
    path("channels/<int:channel_id>/audit-log", ChannelAuditLogView.as_view()),
    path("channels/<int:channel_id>/audit-log/export", ChannelAuditExportView.as_view()),
    path("channels/<int:channel_id>/suggestions", ChannelPlaylistSuggestionView.as_view()),
    path("channels/<int:channel_id>/notification-settings", ChannelNotificationPreferenceView.as_view()),
    path("channels/<int:channel_id>/settings", ChannelSettingsView.as_view()),
    path("channels/<int:channel_id>/members", ChannelMembersView.as_view()),
    path("channels/<int:channel_id>/members/<int:member_id>", ChannelMemberManageView.as_view()),
    path("channels/<int:channel_id>/playlists/shuffle", ChannelShufflePlayView.as_view()),
    path("channels/<int:channel_id>/playlists/<int:playlist_id>/play", ChannelPlayPlaylistView.as_view()),
    path("channels/<int:channel_id>/tracks/<int:track_id>/play", ChannelPlayTrackView.as_view()),
    path("channels/<int:channel_id>/queue", ChannelQueueView.as_view()),
    path("channels/<int:channel_id>/queue/<int:item_id>", ChannelQueueItemManageView.as_view()),
    path("channels/<int:channel_id>/queue/<int:item_id>/jump", ChannelQueueJumpView.as_view()),
    path("channels/<int:channel_id>/queue/<int:item_id>/upvote", ChannelQueueUpvoteView.as_view()),
    path("tracks/upload/init", TrackUploadInitView.as_view()),
    path("tracks/upload/<uuid:upload_id>/status", TrackUploadStatusView.as_view()),
    path("tracks/upload/<uuid:upload_id>/chunk", TrackUploadChunkView.as_view()),
    path("tracks/upload/<uuid:upload_id>/finalize", TrackUploadFinalizeView.as_view()),
    path("tracks/<int:track_id>/share-permissions", TrackSharePermissionsView.as_view()),
    path("", include(router.urls)),
]
