# Generated by Django 4.2.16 on 2026-04-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stream_channels", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaybackEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("emitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlaybackSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at_server_time", models.FloatField(blank=True, null=True)),
                ("paused_at_position", models.FloatField(blank=True, null=True)),
                ("is_playing", models.BooleanField(default=False)),
                ("playback_rate", models.FloatField(default=1.0)),
                ("queue_version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_session",
                        to="stream_channels.channel",
                    ),
                ),
            ],
        ),
    ]
