# Generated by Django 4.2.16 on 2026-04-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tracks", "0001_initial"),
        ("stream_channels", "__first__"),
        ("playback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbacksession",
            name="track",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tracks.track"
            ),
        ),
        migrations.AddField(
            model_name="playbackevent",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playback_events",
                to="stream_channels.channel",
            ),
        ),
    ]
