# Generated by Django 4.2.16 on 2026-05-15 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracks", "0002_track_genre_track_tags"),
        ("playback", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbackevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playback_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playbackevent",
            name="source",
            field=models.CharField(blank=True, default="manual", max_length=32),
        ),
        migrations.AddField(
            model_name="playbackevent",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playback_events",
                to="tracks.track",
            ),
        ),
    ]
