# Generated by Django 4.2.16 on 2026-04-29 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("playlists", "0001_initial"),
        ("tracks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stream_channels", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistitem",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="playlist_items", to="tracks.track"
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="stream_channels.channel",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="playlists", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="channelqueueitem",
            name="added_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="channelqueueitem",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="queue_items", to="stream_channels.channel"
            ),
        ),
        migrations.AddField(
            model_name="channelqueueitem",
            name="track",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tracks.track"),
        ),
    ]
